import type { Metadata } from "next";
import { Bricolage_Grotesque } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { AuthProvider } from "@/context/AuthContext";

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-bricolage",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={bricolage.variable}>
      <body className={"antialiased"}>
        <AuthProvider>
          {children}
        </AuthProvider>

        <ToastContainer
          position="top-right"
          closeButton
        />
      </body>
    </html>
  );
}
